# DATAFRAME WITH EVENT NAME AND DATE

In [1]:
##import libraries request and bs4
import requests #library needed for requesting permission to website
from bs4 import BeautifulSoup #needed for filtering through website html code
import pandas as pd

In [2]:
thislist1 = []
thislist2 = []

for i in range(0,8):
    s = str(i)
    url = "https://www.hetdepot.be/archief?page=" + s
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")
    groups = soup.select('div.calendar__group')
    for group in groups:
        date = group.select_one('h3').text.strip()
        items = group.select('div.calendar-item')
        for item in items:
            title = item.select_one('h2.calendar-item__title').text.strip()
            thislist1.append(title)
            thislist2.append(date)

In [3]:
df_past = pd.DataFrame(thislist1)
df_past.columns = ["Event Name"]
df_past['Date'] = thislist2
df_past

,Event Name,Date
0,K.ZIA,dinsdag09 mei 2023
1,Depot Café presents Porcelain id,maandag08 mei 2023
2,Belpop Bonanza Leuven ...,zaterdag06 mei 2023
3,Belpop Bonanza Leuven ...,vrijdag05 mei 2023
4,RAUW! \n ...,donderdag04 mei 2023
...,...,...
235,Open Mic,woensdag02 feb 2022
236,(Don't) Mind The Future,woensdag02 feb 2022
237,(Don't) Mind The Future,dinsdag01 feb 2022\ntot\ndinsdag01 feb 2022
238,Preselectie Humo's Rock Rally 2022,zaterdag29 jan 2022
239,Stijn Meuris – Tirade #5 – De Stilstand,vrijdag28 jan 2022

# Format 'date' column

In [4]:
#create dataframe only date
df_only_date = df_past.loc[:, ["Date"]]
df_only_date

                                            Date
0                             dinsdag09 mei 2023
1                             maandag08 mei 2023
2                            zaterdag06 mei 2023
3                             vrijdag05 mei 2023
4                           donderdag04 mei 2023
..                                           ...
235                          woensdag02 feb 2022
236                          woensdag02 feb 2022
237  dinsdag01 feb 2022\ntot\ndinsdag01 feb 2022
238                          zaterdag29 jan 2022
239                           vrijdag28 jan 2022

[240 rows x 1 columns]

In [5]:
list1 = []
list2 = []

for i in range(len(df_only_date)):
    ser = df_only_date.loc[i]
    series = ser.to_string()
    all_words = str.split(series)
    if len(all_words) == 4:
        #extract second word of each row
        second_word = all_words[1]
        #split word
        last_two = second_word[-2:]
        rest = second_word[:-2]
        result = rest + " " + last_two 
        #replace
        words = result.split() #split first word
        words[0] = "" #first word replaced with empty space
        new_string = " ".join(words) #adding rest to empty space to get only number
        #get rest of the words
        month = all_words[2] #get third word
        month = str(month) 
        year = all_words[3] #get fourth word
        year = str(year)
        final = year + month + new_string #put together
        new_final = f"{year} {month} {new_string}" #format
        new_final = new_final.replace("jan", "01")
        new_final = new_final.replace('feb', '02')
        new_final = new_final.replace('maa', '03')
        new_final = new_final.replace('apr', '04')
        new_final = new_final.replace('mei', '05')
        new_final = new_final.replace('jun', '06')
        new_final = new_final.replace('jul', '07')
        new_final = new_final.replace('aug', '08')
        new_final = new_final.replace('sep', '09')
        new_final = new_final.replace('okt', '10')
        new_final = new_final.replace('nov', '11')
        new_final = new_final.replace('dec', '12')
        new_final = new_final.replace('  ', ' ')
        new_final = new_final.replace(' ', '-')
        list1.append(new_final)
    else:
        list1.append(new_final)
    if len(all_words) == 6:
        #extract fourth word of each row
        fourth_word = all_words[3]
        #keep only last 2 characters
        last_two_2 = fourth_word[-2:]
        str(last_two)
        #get rest of the words
        month2 = all_words[4] #get fifth word
        month2 = str(month) 
        year2 = all_words[5] #get sixth word
        year2 = str(year)
        final2 = year2 + month2 + last_two_2 #put together
        new_final2 = f"{year2} {month2} {last_two_2}" #format
        new_final2 = new_final2.replace("jan", "01")
        new_final2 = new_final2.replace('feb', '02')
        new_final2 = new_final2.replace('maa', '03')
        new_final2 = new_final2.replace('apr', '04')
        new_final2 = new_final2.replace('mei', '05')
        new_final2 = new_final2.replace('jun', '06')
        new_final2 = new_final2.replace('jul', '07')
        new_final2 = new_final2.replace('aug', '08')
        new_final2 = new_final2.replace('sep', '09')
        new_final2 = new_final2.replace('okt', '10')
        new_final2 = new_final2.replace('nov', '11')
        new_final2 = new_final2.replace('dec', '12')
        new_final2 = new_final2.replace('  ', ' ')
        new_final2 = new_final2.replace(' ', '-')
        list2.append(new_final2)
    else:
        list2.append(new_final)

# Create final DataFrame

In [6]:
df_past = pd.DataFrame(thislist1)
df_past.columns = ["Event Name"]
df_past["StartDate"] = list1
df_past["EndDate"] = list2
df_past

                                            Event Name   StartDate     EndDate
0                                                K.ZIA  2023-05-09  2023-05-09
1                     Depot Café presents Porcelain id  2023-05-08  2023-05-08
2    Belpop Bonanza Leuven                         ...  2023-05-06  2023-05-06
3    Belpop Bonanza Leuven                         ...  2023-05-05  2023-05-05
4    RAUW!                             \n          ...  2023-05-04  2023-05-04
..                                                 ...         ...         ...
235                                           Open Mic  2022-02-02  2022-02-02
236                            (Don't) Mind The Future  2022-02-02  2022-02-02
237                            (Don't) Mind The Future  2022-02-02  2022-02-01
238                 Preselectie Humo's Rock Rally 2022  2022-01-29  2022-01-29
239            Stijn Meuris – Tirade #5 – De Stilstand  2022-01-28  2022-01-28

[240 rows x 3 columns]

In [ ]:
#csv
df_past.to_csv('past_events.csv', index=False)