# DATAFRAME WITH EVENT NAME AND DATE

In [1]:
##import libraries request and bs4
import requests #library needed for requesting permission to website
from bs4 import BeautifulSoup #needed for filtering through website html code
import pandas as pd

In [2]:
thislist1 = []
thislist2 = []

for i in range(0,2):
    s = str(i)
    url = "https://www.hetdepot.be/programma?page=" + s
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")
    groups = soup.select('div.calendar__group')
    for group in groups:
        date = group.select_one('h3').text.strip()
        items = group.select('div.calendar-item')
        for item in items:
            title = item.select_one('h2.calendar-item__title').text.strip()
            thislist1.append(title)
            thislist2.append(date)

In [3]:
df_next = pd.DataFrame(thislist1)
df_next.columns = ["Event Name"]
df_next['Date'] = thislist2
df_next

,Event Name,Date
0,CLUB VISMARKT,vrijdag07 jul 2023\ntot\ndonderdag20 jul 2023
1,M-IDZOMER 2023: José González + Marble Sounds ...,donderdag27 jul 2023\ntot\ndonderdag27 jul 2023
2,M-IDZOMER 2023: Thurston Moore Group + King Ha...,vrijdag28 jul 2023\ntot\nvrijdag28 jul 2023
3,M-IDZOMER FOR KIDS: Kapitein Winokio,zaterdag29 jul 2023\ntot\nzaterdag29 jul 2023
4,M-IDZOMER 2023: DAAN + Calicos + Pitou + Zimme...,zaterdag29 jul 2023\ntot\nzaterdag29 jul 2023
...,...,...
109,Lloyd Cole,zondag05 nov 2023
110,Portland \n ...,dinsdag07 nov 2023
111,Portland \n ...,dinsdag07 nov 2023
112,Portland \n ...,woensdag08 nov 2023
113,Ão,vrijdag10 nov 2023

# Format 'date' column

In [4]:
#create dataframe only date
df_only_date = df_next.loc[:, ["Date"]]
df_only_date

                                                Date
0      vrijdag07 jul 2023\ntot\ndonderdag20 jul 2023
1    donderdag27 jul 2023\ntot\ndonderdag27 jul 2023
2        vrijdag28 jul 2023\ntot\nvrijdag28 jul 2023
3      zaterdag29 jul 2023\ntot\nzaterdag29 jul 2023
4      zaterdag29 jul 2023\ntot\nzaterdag29 jul 2023
..                                               ...
109                                zondag05 nov 2023
110                               dinsdag07 nov 2023
111                               dinsdag07 nov 2023
112                              woensdag08 nov 2023
113                               vrijdag10 nov 2023

[114 rows x 1 columns]

In [5]:
list1 = []
list2 = []

for i in range(len(df_only_date)):
    ser = df_only_date.loc[i]
    series = ser.to_string()
    all_words = str.split(series)
    if len(all_words) == 4:
        #extract second word of each row
        second_word = all_words[1]
        #split word
        last_two = second_word[-2:]
        rest = second_word[:-2]
        result = rest + " " + last_two 
        #replace
        words = result.split() #split first word
        words[0] = "" #first word replaced with empty space
        new_string = " ".join(words) #adding rest to empty space to get only number
        #get rest of the words
        month = all_words[2] #get third word
        month = str(month) 
        year = all_words[3] #get fourth word
        year = str(year)
        final = year + month + new_string #put together
        new_final = f"{year} {month} {new_string}" #format
        new_final = new_final.replace("jan", "01")
        new_final = new_final.replace('feb', '02')
        new_final = new_final.replace('mrt', '03')
        new_final = new_final.replace('apr', '04')
        new_final = new_final.replace('mei', '05')
        new_final = new_final.replace('jun', '06')
        new_final = new_final.replace('jul', '07')
        new_final = new_final.replace('aug', '08')
        new_final = new_final.replace('sep', '09')
        new_final = new_final.replace('okt', '10')
        new_final = new_final.replace('nov', '11')
        new_final = new_final.replace('dec', '12')
        new_final = new_final.replace('  ', ' ')
        new_final = new_final.replace(' ', '-')
        list1.append(new_final)
    else:
        #extract second word of each row
        second_word2 = all_words[1]
        last_two2 = second_word2[-2:]
        rest2 = second_word2[:-2]
        result2 = rest2 + " " + last_two2
        #replace
        words2 = result2.split() #split first word
        words2[0] = "" #first word replaced with empty space
        new_string2 = " ".join(words2) #adding rest to empty space to get only number
        #get month
        month2 = all_words[2] #get third word
        month2 = str(month2) 
        #extract year (fourth word)
        fourth_word = all_words[3]
        #keep only first 4 characters
        first_four = fourth_word[:4]
        str(first_four)
        final_ee = first_four + month2 + new_string2 #put together
        final_e = f"{first_four} {month2} {new_string2}" #format
        final_e = final_e.replace("jan", "01")
        final_e = final_e.replace('feb', '02')
        final_e = final_e.replace('mrt', '03')
        final_e = final_e.replace('apr', '04')
        final_e = final_e.replace('mei', '05')
        final_e = final_e.replace('jun', '06')
        final_e = final_e.replace('jul', '07')
        final_e = final_e.replace('aug', '08')
        final_e = final_e.replace('sep', '09')
        final_e = final_e.replace('okt', '10')
        final_e = final_e.replace('nov', '11')
        final_e = final_e.replace('dec', '12')
        final_e = final_e.replace('  ', ' ')
        final_e = final_e.replace(' ', '-')
        list1.append(final_e)
    if len(all_words) == 6:
        #extract fourth word of each row
        fourth_word = all_words[3]
        #keep only last 2 characters
        last_two3 = fourth_word[-2:]
        str(last_two3)
        #get rest of the words
        month3 = all_words[4] #get fifth word
        month3 = str(month3) 
        year3 = all_words[5] #get sixth word
        year3 = str(year3)
        final3 = year3 + month3 + last_two3 #put together
        new_final2 = f"{year3} {month3} {last_two3}" #format
        new_final2 = new_final2.replace("jan", "01")
        new_final2 = new_final2.replace('feb', '02')
        new_final2 = new_final2.replace('mrt', '03')
        new_final2 = new_final2.replace('apr', '04')
        new_final2 = new_final2.replace('mei', '05')
        new_final2 = new_final2.replace('jun', '06')
        new_final2 = new_final2.replace('jul', '07')
        new_final2 = new_final2.replace('aug', '08')
        new_final2 = new_final2.replace('sep', '09')
        new_final2 = new_final2.replace('okt', '10')
        new_final2 = new_final2.replace('nov', '11')
        new_final2 = new_final2.replace('dec', '12')
        new_final2 = new_final2.replace('  ', ' ')
        new_final2 = new_final2.replace(' ', '-')
        list2.append(new_final2)
    else:
        list2.append(new_final)

# Create final DataFrame

In [6]:
df_next = pd.DataFrame(thislist1)
df_next.columns = ["Event Name"]
df_next["StartDate"] = list1
df_next["EndDate"] = list2
df_next[:30]

                                           Event Name   StartDate     EndDate
0                                       CLUB VISMARKT  2023-07-07  2023-07-20
1   M-IDZOMER 2023: José González + Marble Sounds ...  2023-07-27  2023-07-27
2   M-IDZOMER 2023: Thurston Moore Group + King Ha...  2023-07-28  2023-07-28
3                M-IDZOMER FOR KIDS: Kapitein Winokio  2023-07-29  2023-07-29
4   M-IDZOMER 2023: DAAN + Calicos + Pitou + Zimme...  2023-07-29  2023-07-29
5   M-IDZOMER 2023: Suzanne Vega + Alela Diane + K...  2023-07-30  2023-07-30
6   Jean-Marie Aerts                             \...  2023-09-15  2023-09-15
7                  Scott Bradlee's Postmodern Jukebox  2023-09-16  2023-09-16
8   Half Moon Run + \n          Flyte\n      \n   ...  2023-09-20  2023-09-20
9                 Sunn O))) + \n          Aluk Todolo  2023-09-22  2023-09-22
10  Patrick Watson + \n          La Force\n      \...  2023-09-27  2023-09-27
11  Patrick Watson + \n          La Force\n      \...  2023-09-28  2023-09-28
12                                     Maaike Ouboter  2023-09-29  2023-09-29
13                        COOL presents Kendra Morris  2023-10-03  2023-10-03
14  COOL presents Theo Katzman                    ...  2023-10-07  2023-10-07
15                                            Isbells  2023-10-10  2023-10-10
16                           Mr. Paul & The Lowriders  2023-10-13  2023-10-13
17                                      Frank Boeijen  2023-10-14  2023-10-14
18                                           Capleton  2023-10-15  2023-10-15
19                                          Jazz Brak  2023-10-17  2023-10-17
20                      JP Cooper + \n          Jerub  2023-10-18  2023-10-18
21                               Black Box Revelation  2023-10-21  2023-10-21
22                Het Depot & INUIT present overdrive  2023-10-26  2023-10-26
23                                              Coely  2023-11-02  2023-11-02
24                Elder + \n          Slomosa + Gnome  2023-11-03  2023-11-03
25                                         Lloyd Cole  2023-11-05  2023-11-05
26  Portland                             \n       ...  2023-11-07  2023-11-07
27  Portland                             \n       ...  2023-11-07  2023-11-07
28  Portland                             \n       ...  2023-11-08  2023-11-08
29                                                 Ão  2023-11-10  2023-11-10

In [ ]:
#csv
df_next.head(30).to_csv('next_events.csv', index=False)