In [4]:
import pandas as pd
#load the data
dfs = []
# Loop through the filenames and read the dataframes
for i in range(1, 10):
    filename = f"df_{i:02d}.csv"  # Format the filename with leading zeros
    filepath = f"/Users/stefbp/Documents/GitHub/MDA_project/noise prediction model/Past Data matrix/{filename}"
    df = pd.read_csv(filepath)
    dfs.append(df)
df = pd.concat(dfs, ignore_index=True)
df[['date', 'day']] = df[['date', 'day']].apply(lambda x: pd.to_datetime(x)) #reading it from the raw file returns string dtypes for the time variables.
#variable time is left untouched.
df['hour'] = df['date'].dt.hour
df['night'] = df['hour'].apply(lambda x: 1 if x >= 20 or x < 6 else 0)

In [38]:
df.head(2)

,date,day,time,weekday,LC_HUMIDITY,LC_RAININ,LC_TEMP_QCL3_list,school,loko,depot,location,Latitude,Longitude,laf50_per_hour,hour,night,weekday_status,weekend_status
0,2022-01-01 00:00:00,2022-01-01,00:00-01:00,Saturday,89.257143,0.0,13.076508,0.0,0.0,0.0,Number 35,50.877146,4.700688,NaN,0,1,1,1
1,2022-01-01 01:00:00,2022-01-01,01:00-02:00,Saturday,88.333333,0.0,13.079861,0.0,0.0,0.0,Number 35,50.877146,4.700688,NaN,1,1,1,1

In [31]:
import numpy as np
df['weekend_status'] = pd.DataFrame(np.where(df['weekday'].isin(['Saturday', 'Sunday']), 1, 0))

36 baselines:
- 9 spots
- 2 categories of week (weekend/weekday)
- 2 categories of hours (night/day)

In [32]:
baselines = df.groupby(['location', 'weekend_status', 'night'])['laf50_per_hour'].mean().reset_index()
baselines['weekend_status'] = baselines['weekend_status'].apply(lambda x: 'Weekend' if x == 1 else 'Weekday')
baselines['night'] = baselines['night'].apply(lambda x: 'Night' if x == 1 else 'Day')

In [36]:
baselines

,location,weekend_status,night,laf50_per_hour
0,Calvarie Chapel (near the Faculty of Economics),Weekday,Day,54.076736
1,Calvarie Chapel (near the Faculty of Economics),Weekday,Night,44.861644
2,Calvarie Chapel (near the Faculty of Economics),Weekend,Day,49.027416
3,Calvarie Chapel (near the Faculty of Economics),Weekend,Night,44.934763
4,Corner of the Parkstraat & Naamse straat,Weekday,Day,55.271857
5,Corner of the Parkstraat & Naamse straat,Weekday,Night,44.810380
6,Corner of the Parkstraat & Naamse straat,Weekend,Day,49.077002
7,Corner of the Parkstraat & Naamse straat,Weekend,Night,44.940484
8,Kiosk Stadspark,Weekday,Day,NaN
9,Kiosk Stadspark,Weekday,Night,NaN
10,Kiosk Stadspark,Weekend,Day,NaN
11,Kiosk Stadspark,Weekend,Night,NaN
12,Number 35,Weekday,Day,53.243815
13,Number 35,Weekday,Night,49.667618
14,Number 35,Weekend,Day,48.764934
15,Number 35,Weekend,Night,48.898419
16,Number 57,Weekday,Day,53.670416
17,Number 57,Weekday,Night,46.299948
18,Number 57,Weekend,Day,49.528325
19,Number 57,Weekend,Night,46.620424
20,Number 62,Weekday,Day,54.860447
21,Number 62,Weekday,Night,49.317609
22,Number 62,Weekend,Day,51.356068
23,Number 62,Weekend,Night,49.016254
24,"Number 76 (""His & Hears” Hair salon in Leuven)",Weekday,Day,55.836364
25,"Number 76 (""His & Hears” Hair salon in Leuven)",Weekday,Night,49.701818
26,"Number 76 (""His & Hears” Hair salon in Leuven)",Weekend,Day,51.647138
27,"Number 76 (""His & Hears” Hair salon in Leuven)",Weekend,Night,48.319626
28,Number 81,Weekday,Day,55.120640
29,Number 81,Weekday,Night,42.226266
30,Number 81,Weekend,Day,47.888566
31,Number 81,Weekend,Night,42.672692
32,Vrijthof,Weekday,Day,45.041885
33,Vrijthof,Weekday,Night,42.636839
34,Vrijthof,Weekend,Day,44.221333
35,Vrijthof,Weekend,Night,43.551200

In [37]:
baselines.to_csv('baselines.csv',sep=';')